


















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ServiceStackExamples`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost\SQLExpress;Initial Catalog=ServiceStackExamples;Integrated Security=SSPI`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
 