


















 


// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `ServiceStackExamples`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=localhost\SQLExpress;Initial Catalog=ServiceStackExamples;Integrated Security=SSPI`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace ServiceStackExamples
{
	[Alias("Factura")]
    public partial class Factura : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set; }
        public string Numero { get; set; }
        [Required]
        public DateTime Fecha { get; set; }
    }

	[Alias("LineaFactura")]
    public partial class LineaFactura : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set; }
        [Required]
        public long FacturaId { get; set; }
        [Required]
        public long ProductoId { get; set; }
        [Required]
        public decimal Precio { get; set; }
        [Required]
        public int Unidades { get; set; }
    }

	[Alias("Persona")]
    public partial class Persona : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set; }
        public string Nombre { get; set; }
        public DateTime? FechaNacimiento { get; set; }
        public string Direccion { get; set; }
    }

	[Alias("Producto")]
    public partial class Producto : IHasId<long> 
    {
        [Alias("Id")]
        [AutoIncrement]
        public long Id { get; set; }
        public string Nombre { get; set; }
    }

}
#pragma warning restore 1591
